name: An Introduction to PDB2PQR
category: setup
authors: ""
shortdesc: This short course illustrates the application of pdb2pqr to the analysis of the tautomeric and ionization states of residues in the structure of the cysteine protease cruzein (PDB code 2oz2) - the results may not be what you would have expected!
longdesc: ""
